title: "ソフトウェア開発の原則と実践"
summary: "本ブックでは、ソフトウェア開発における成功の秘訣、円滑なコミュニケーション術、要件定義の重要性、協調性を生むプログラマの思想、迅速な開発アプローチ、プロフェッショナルな行動規範、品質管理の歴史と現代的アプローチ、意思決定の極意、チームにおける属人性の解消、そして情報伝達のガイドラインについて幅広く解説します。"
topics:
  - software-development
  - agile
  - communication
  - quality-management
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - how-software-succeeds
  - smooth-communication-in-product-development
  - introduction-to-requirements-definition
  - programmer-philosophy-qiitaconference
  - build-first-accelerates-everything
  - example6
  - example7
  - example8
  - example9
  - example10
  - example11
  - example12
